/*
 * This file is generated by jOOQ.
 */
package com.witalis.jkit.jooq.model.tables.records;


import com.witalis.jkit.jooq.model.enums.PlanetType;
import com.witalis.jkit.jooq.model.tables.Planet;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Entity representing planet.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlanetRecord extends UpdatableRecordImpl<PlanetRecord> implements Record6<Long, String, Long, PlanetType, String, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>astronomy.planet.id</code>. Planet identifier. Primary
     * Key.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>astronomy.planet.id</code>. Planet identifier. Primary
     * Key.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>astronomy.planet.name</code>. Name of the planet.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>astronomy.planet.name</code>. Name of the planet.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>astronomy.planet.system_id</code>. ID of the planet
     * system.
     */
    public void setSystemId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>astronomy.planet.system_id</code>. ID of the planet
     * system.
     */
    public Long getSystemId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>astronomy.planet.type</code>. Type of the planet.
     */
    public void setType(PlanetType value) {
        set(3, value);
    }

    /**
     * Getter for <code>astronomy.planet.type</code>. Type of the planet.
     */
    public PlanetType getType() {
        return (PlanetType) get(3);
    }

    /**
     * Setter for <code>astronomy.planet.sign</code>. Sign of the planet.
     */
    public void setSign(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>astronomy.planet.sign</code>. Sign of the planet.
     */
    public String getSign() {
        return (String) get(4);
    }

    /**
     * Setter for <code>astronomy.planet.note</code>. Note of the planet.
     */
    public void setNote(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>astronomy.planet.note</code>. Note of the planet.
     */
    public String getNote() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, Long, PlanetType, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, Long, PlanetType, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Planet.PLANET.ID;
    }

    @Override
    public Field<String> field2() {
        return Planet.PLANET.NAME;
    }

    @Override
    public Field<Long> field3() {
        return Planet.PLANET.SYSTEM_ID;
    }

    @Override
    public Field<PlanetType> field4() {
        return Planet.PLANET.TYPE;
    }

    @Override
    public Field<String> field5() {
        return Planet.PLANET.SIGN;
    }

    @Override
    public Field<String> field6() {
        return Planet.PLANET.NOTE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Long component3() {
        return getSystemId();
    }

    @Override
    public PlanetType component4() {
        return getType();
    }

    @Override
    public String component5() {
        return getSign();
    }

    @Override
    public String component6() {
        return getNote();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Long value3() {
        return getSystemId();
    }

    @Override
    public PlanetType value4() {
        return getType();
    }

    @Override
    public String value5() {
        return getSign();
    }

    @Override
    public String value6() {
        return getNote();
    }

    @Override
    public PlanetRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PlanetRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public PlanetRecord value3(Long value) {
        setSystemId(value);
        return this;
    }

    @Override
    public PlanetRecord value4(PlanetType value) {
        setType(value);
        return this;
    }

    @Override
    public PlanetRecord value5(String value) {
        setSign(value);
        return this;
    }

    @Override
    public PlanetRecord value6(String value) {
        setNote(value);
        return this;
    }

    @Override
    public PlanetRecord values(Long value1, String value2, Long value3, PlanetType value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlanetRecord
     */
    public PlanetRecord() {
        super(Planet.PLANET);
    }

    /**
     * Create a detached, initialised PlanetRecord
     */
    public PlanetRecord(Long id, String name, Long systemId, PlanetType type, String sign, String note) {
        super(Planet.PLANET);

        setId(id);
        setName(name);
        setSystemId(systemId);
        setType(type);
        setSign(sign);
        setNote(note);
    }

    /**
     * Create a detached, initialised PlanetRecord
     */
    public PlanetRecord(com.witalis.jkit.jooq.model.tables.pojos.Planet value) {
        super(Planet.PLANET);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setSystemId(value.getSystemId());
            setType(value.getType());
            setSign(value.getSign());
            setNote(value.getNote());
        }
    }
}
