/*
 * This file is generated by jOOQ.
 */
package com.witalis.jkit.jooq.model.tables.records;


import com.witalis.jkit.jooq.model.tables.PlanetMoon;

import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * Entity representing planet moon.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlanetMoonRecord extends UpdatableRecordImpl<PlanetMoonRecord> implements Record6<Long, Long, String, BigDecimal, BigDecimal, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>astronomy.planet_moon.id</code>. Planet moon identifier.
     * Primary Key.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>astronomy.planet_moon.id</code>. Planet moon identifier.
     * Primary Key.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>astronomy.planet_moon.planet_id</code>. Owning planet
     * identifier. Foreign Key.
     */
    public void setPlanetId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>astronomy.planet_moon.planet_id</code>. Owning planet
     * identifier. Foreign Key.
     */
    public Long getPlanetId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>astronomy.planet_moon.name</code>. Name of the planet
     * moon.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>astronomy.planet_moon.name</code>. Name of the planet
     * moon.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>astronomy.planet_moon.distance</code>. Distance of the
     * planet moon.
     */
    public void setDistance(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>astronomy.planet_moon.distance</code>. Distance of the
     * planet moon.
     */
    public BigDecimal getDistance() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>astronomy.planet_moon.radius</code>. Radius of the
     * planet moon.
     */
    public void setRadius(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>astronomy.planet_moon.radius</code>. Radius of the
     * planet moon.
     */
    public BigDecimal getRadius() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>astronomy.planet_moon.note</code>. Note of the planet
     * moon.
     */
    public void setNote(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>astronomy.planet_moon.note</code>. Note of the planet
     * moon.
     */
    public String getNote() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, String, BigDecimal, BigDecimal, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, String, BigDecimal, BigDecimal, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return PlanetMoon.PLANET_MOON.ID;
    }

    @Override
    public Field<Long> field2() {
        return PlanetMoon.PLANET_MOON.PLANET_ID;
    }

    @Override
    public Field<String> field3() {
        return PlanetMoon.PLANET_MOON.NAME;
    }

    @Override
    public Field<BigDecimal> field4() {
        return PlanetMoon.PLANET_MOON.DISTANCE;
    }

    @Override
    public Field<BigDecimal> field5() {
        return PlanetMoon.PLANET_MOON.RADIUS;
    }

    @Override
    public Field<String> field6() {
        return PlanetMoon.PLANET_MOON.NOTE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getPlanetId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public BigDecimal component4() {
        return getDistance();
    }

    @Override
    public BigDecimal component5() {
        return getRadius();
    }

    @Override
    public String component6() {
        return getNote();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getPlanetId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public BigDecimal value4() {
        return getDistance();
    }

    @Override
    public BigDecimal value5() {
        return getRadius();
    }

    @Override
    public String value6() {
        return getNote();
    }

    @Override
    public PlanetMoonRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PlanetMoonRecord value2(Long value) {
        setPlanetId(value);
        return this;
    }

    @Override
    public PlanetMoonRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public PlanetMoonRecord value4(BigDecimal value) {
        setDistance(value);
        return this;
    }

    @Override
    public PlanetMoonRecord value5(BigDecimal value) {
        setRadius(value);
        return this;
    }

    @Override
    public PlanetMoonRecord value6(String value) {
        setNote(value);
        return this;
    }

    @Override
    public PlanetMoonRecord values(Long value1, Long value2, String value3, BigDecimal value4, BigDecimal value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlanetMoonRecord
     */
    public PlanetMoonRecord() {
        super(PlanetMoon.PLANET_MOON);
    }

    /**
     * Create a detached, initialised PlanetMoonRecord
     */
    public PlanetMoonRecord(Long id, Long planetId, String name, BigDecimal distance, BigDecimal radius, String note) {
        super(PlanetMoon.PLANET_MOON);

        setId(id);
        setPlanetId(planetId);
        setName(name);
        setDistance(distance);
        setRadius(radius);
        setNote(note);
    }

    /**
     * Create a detached, initialised PlanetMoonRecord
     */
    public PlanetMoonRecord(com.witalis.jkit.jooq.model.tables.pojos.PlanetMoon value) {
        super(PlanetMoon.PLANET_MOON);

        if (value != null) {
            setId(value.getId());
            setPlanetId(value.getPlanetId());
            setName(value.getName());
            setDistance(value.getDistance());
            setRadius(value.getRadius());
            setNote(value.getNote());
        }
    }
}
