# server
server:
  address: 0.0.0.0
  port: 9000
  servlet:
    context-path: /flyway
# spring
spring:
  application:
    name: jkit-flyway
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/flyway
    username: flyway
    password: flyway
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 10
      pool-name: postgres-pool
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
    generate-ddl: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        auto_quote_keyword: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        highlight_sql: true
        generate_statistics: false
        globally_quoted_identifiers: false
        globally_quoted_identifiers_skip_column_definitions: false
        hbm2ddl:
          auto: none
        jdbc:
          batch_size: 50
          batch_versioned_data: true
          fetch_size: 50
        order_inserts: true
        order_updates: true
        show_sql: true
        use_sql_comments: true
    show-sql: true
  sql:
    init:
      mode:
  flyway:
    baseline-version: 1
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-on-validation-error: true
    create-schemas: true
    enabled: true
    sql-migration-prefix: 'v'
    sql-migration-separator: '--'
    table: flyway_schema_history
    url: 'jdbc:postgresql://localhost:5432/flyway'
    user: 'flyway'
    password: 'flyway'
    schemas: ['astronomy', 'public']
    locations: ['classpath:db/migration']
# logging
logging:
  config: classpath:logging/log4j2.yml
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: INFO
