/*
 * This file is generated by jOOQ.
 */
package com.witalis.jkit.jooq.model.tables.pojos;


import java.io.Serializable;


/**
 * Entity representing planet atmosphere mapping.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlanetAtmosphereMap implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long planetId;
    private Long atmosphereId;

    public PlanetAtmosphereMap() {}

    public PlanetAtmosphereMap(PlanetAtmosphereMap value) {
        this.planetId = value.planetId;
        this.atmosphereId = value.atmosphereId;
    }

    public PlanetAtmosphereMap(
        Long planetId,
        Long atmosphereId
    ) {
        this.planetId = planetId;
        this.atmosphereId = atmosphereId;
    }

    /**
     * Getter for <code>astronomy.planet_atmosphere_map.planet_id</code>.
     * Reference to the planet identifier.
     */
    public Long getPlanetId() {
        return this.planetId;
    }

    /**
     * Setter for <code>astronomy.planet_atmosphere_map.planet_id</code>.
     * Reference to the planet identifier.
     */
    public void setPlanetId(Long planetId) {
        this.planetId = planetId;
    }

    /**
     * Getter for <code>astronomy.planet_atmosphere_map.atmosphere_id</code>.
     * Reference to the planet atmosphere identifier.
     */
    public Long getAtmosphereId() {
        return this.atmosphereId;
    }

    /**
     * Setter for <code>astronomy.planet_atmosphere_map.atmosphere_id</code>.
     * Reference to the planet atmosphere identifier.
     */
    public void setAtmosphereId(Long atmosphereId) {
        this.atmosphereId = atmosphereId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PlanetAtmosphereMap other = (PlanetAtmosphereMap) obj;
        if (this.planetId == null) {
            if (other.planetId != null)
                return false;
        }
        else if (!this.planetId.equals(other.planetId))
            return false;
        if (this.atmosphereId == null) {
            if (other.atmosphereId != null)
                return false;
        }
        else if (!this.atmosphereId.equals(other.atmosphereId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.planetId == null) ? 0 : this.planetId.hashCode());
        result = prime * result + ((this.atmosphereId == null) ? 0 : this.atmosphereId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PlanetAtmosphereMap (");

        sb.append(planetId);
        sb.append(", ").append(atmosphereId);

        sb.append(")");
        return sb.toString();
    }
}
