/*
 * This file is generated by jOOQ.
 */
package com.witalis.jkit.jooq.model.tables.pojos;


import java.io.Serializable;


/**
 * Entity representing planet system.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlanetSystem implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private Long age;
    private Integer stars;
    private String location;
    private String note;

    public PlanetSystem() {}

    public PlanetSystem(PlanetSystem value) {
        this.id = value.id;
        this.name = value.name;
        this.age = value.age;
        this.stars = value.stars;
        this.location = value.location;
        this.note = value.note;
    }

    public PlanetSystem(
        Long id,
        String name,
        Long age,
        Integer stars,
        String location,
        String note
    ) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.stars = stars;
        this.location = location;
        this.note = note;
    }

    /**
     * Getter for <code>astronomy.planet_system.id</code>. Planet system
     * identifier. Primary Key.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>astronomy.planet_system.id</code>. Planet system
     * identifier. Primary Key.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>astronomy.planet_system.name</code>. Name of the planet
     * system.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>astronomy.planet_system.name</code>. Name of the planet
     * system.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>astronomy.planet_system.age</code>. Age of the planet
     * system.
     */
    public Long getAge() {
        return this.age;
    }

    /**
     * Setter for <code>astronomy.planet_system.age</code>. Age of the planet
     * system.
     */
    public void setAge(Long age) {
        this.age = age;
    }

    /**
     * Getter for <code>astronomy.planet_system.stars</code>. Number of stars
     * into the planet system.
     */
    public Integer getStars() {
        return this.stars;
    }

    /**
     * Setter for <code>astronomy.planet_system.stars</code>. Number of stars
     * into the planet system.
     */
    public void setStars(Integer stars) {
        this.stars = stars;
    }

    /**
     * Getter for <code>astronomy.planet_system.location</code>. Location of the
     * planet system.
     */
    public String getLocation() {
        return this.location;
    }

    /**
     * Setter for <code>astronomy.planet_system.location</code>. Location of the
     * planet system.
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * Getter for <code>astronomy.planet_system.note</code>. Note of the planet
     * system.
     */
    public String getNote() {
        return this.note;
    }

    /**
     * Setter for <code>astronomy.planet_system.note</code>. Note of the planet
     * system.
     */
    public void setNote(String note) {
        this.note = note;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PlanetSystem other = (PlanetSystem) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.age == null) {
            if (other.age != null)
                return false;
        }
        else if (!this.age.equals(other.age))
            return false;
        if (this.stars == null) {
            if (other.stars != null)
                return false;
        }
        else if (!this.stars.equals(other.stars))
            return false;
        if (this.location == null) {
            if (other.location != null)
                return false;
        }
        else if (!this.location.equals(other.location))
            return false;
        if (this.note == null) {
            if (other.note != null)
                return false;
        }
        else if (!this.note.equals(other.note))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.age == null) ? 0 : this.age.hashCode());
        result = prime * result + ((this.stars == null) ? 0 : this.stars.hashCode());
        result = prime * result + ((this.location == null) ? 0 : this.location.hashCode());
        result = prime * result + ((this.note == null) ? 0 : this.note.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PlanetSystem (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(age);
        sb.append(", ").append(stars);
        sb.append(", ").append(location);
        sb.append(", ").append(note);

        sb.append(")");
        return sb.toString();
    }
}
