/*
 * This file is generated by jOOQ.
 */
package com.witalis.jkit.jooq.model.tables.pojos;


import com.witalis.jkit.jooq.model.enums.PlanetType;

import java.io.Serializable;


/**
 * Entity representing planet.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Planet implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private Long systemId;
    private PlanetType type;
    private String sign;
    private String note;

    public Planet() {}

    public Planet(Planet value) {
        this.id = value.id;
        this.name = value.name;
        this.systemId = value.systemId;
        this.type = value.type;
        this.sign = value.sign;
        this.note = value.note;
    }

    public Planet(
        Long id,
        String name,
        Long systemId,
        PlanetType type,
        String sign,
        String note
    ) {
        this.id = id;
        this.name = name;
        this.systemId = systemId;
        this.type = type;
        this.sign = sign;
        this.note = note;
    }

    /**
     * Getter for <code>astronomy.planet.id</code>. Planet identifier. Primary
     * Key.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>astronomy.planet.id</code>. Planet identifier. Primary
     * Key.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>astronomy.planet.name</code>. Name of the planet.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>astronomy.planet.name</code>. Name of the planet.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>astronomy.planet.system_id</code>. ID of the planet
     * system.
     */
    public Long getSystemId() {
        return this.systemId;
    }

    /**
     * Setter for <code>astronomy.planet.system_id</code>. ID of the planet
     * system.
     */
    public void setSystemId(Long systemId) {
        this.systemId = systemId;
    }

    /**
     * Getter for <code>astronomy.planet.type</code>. Type of the planet.
     */
    public PlanetType getType() {
        return this.type;
    }

    /**
     * Setter for <code>astronomy.planet.type</code>. Type of the planet.
     */
    public void setType(PlanetType type) {
        this.type = type;
    }

    /**
     * Getter for <code>astronomy.planet.sign</code>. Sign of the planet.
     */
    public String getSign() {
        return this.sign;
    }

    /**
     * Setter for <code>astronomy.planet.sign</code>. Sign of the planet.
     */
    public void setSign(String sign) {
        this.sign = sign;
    }

    /**
     * Getter for <code>astronomy.planet.note</code>. Note of the planet.
     */
    public String getNote() {
        return this.note;
    }

    /**
     * Setter for <code>astronomy.planet.note</code>. Note of the planet.
     */
    public void setNote(String note) {
        this.note = note;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Planet other = (Planet) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.systemId == null) {
            if (other.systemId != null)
                return false;
        }
        else if (!this.systemId.equals(other.systemId))
            return false;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        if (this.sign == null) {
            if (other.sign != null)
                return false;
        }
        else if (!this.sign.equals(other.sign))
            return false;
        if (this.note == null) {
            if (other.note != null)
                return false;
        }
        else if (!this.note.equals(other.note))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.systemId == null) ? 0 : this.systemId.hashCode());
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.sign == null) ? 0 : this.sign.hashCode());
        result = prime * result + ((this.note == null) ? 0 : this.note.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Planet (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(systemId);
        sb.append(", ").append(type);
        sb.append(", ").append(sign);
        sb.append(", ").append(note);

        sb.append(")");
        return sb.toString();
    }
}
