/*
 * This file is generated by jOOQ.
 */
package com.witalis.jkit.jooq.model.tables.pojos;


import java.io.Serializable;


/**
 * Entity representing planet atmosphere.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlanetAtmosphere implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private String note;

    public PlanetAtmosphere() {}

    public PlanetAtmosphere(PlanetAtmosphere value) {
        this.id = value.id;
        this.name = value.name;
        this.note = value.note;
    }

    public PlanetAtmosphere(
        Long id,
        String name,
        String note
    ) {
        this.id = id;
        this.name = name;
        this.note = note;
    }

    /**
     * Getter for <code>astronomy.planet_atmosphere.id</code>. Planet atmosphere
     * identifier. Primary Key.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>astronomy.planet_atmosphere.id</code>. Planet atmosphere
     * identifier. Primary Key.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>astronomy.planet_atmosphere.name</code>. Name of the
     * planet atmosphere.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>astronomy.planet_atmosphere.name</code>. Name of the
     * planet atmosphere.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>astronomy.planet_atmosphere.note</code>. Note of the
     * planet atmosphere.
     */
    public String getNote() {
        return this.note;
    }

    /**
     * Setter for <code>astronomy.planet_atmosphere.note</code>. Note of the
     * planet atmosphere.
     */
    public void setNote(String note) {
        this.note = note;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PlanetAtmosphere other = (PlanetAtmosphere) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.note == null) {
            if (other.note != null)
                return false;
        }
        else if (!this.note.equals(other.note))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.note == null) ? 0 : this.note.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PlanetAtmosphere (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(note);

        sb.append(")");
        return sb.toString();
    }
}
