# server
server:
  address: 0.0.0.0
  port: 9000
  servlet:
    context-path: /jooq
# spring
spring:
  application:
    name: jkit-jooq
  main:
    banner-mode: off
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/jooq
    username: jooq
    password: jooq
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 10000
      maximum-pool-size: 10
      pool-name: postgres-pool
  jooq:
    sql-dialect: postgres
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
    generate-ddl: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        auto_quote_keyword: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        highlight_sql: true
        generate_statistics: false
        globally_quoted_identifiers: false
        globally_quoted_identifiers_skip_column_definitions: false
        hbm2ddl:
          auto: validate
        jdbc:
          batch_size: 50
          batch_versioned_data: true
          fetch_size: 50
        order_inserts: true
        order_updates: true
        show_sql: true
        use_sql_comments: true
    show-sql: true
  sql:
    init:
      mode: never
# logging
logging:
  config: classpath:logging/log4j2.yml
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: INFO
