-- user
CREATE USER IF NOT EXISTS jooq PASSWORD 'jooq' ADMIN;
-- schema
CREATE SCHEMA IF NOT EXISTS ASTRONOMY AUTHORIZATION jooq;
-- setup
SET SCHEMA ASTRONOMY;

-- type
CREATE TYPE PLANET_TYPE AS ENUM (
    'GIANT', 'DWARF', 'TERRESTRIAL'
);

-- table
CREATE TABLE PLANET_SYSTEM (
    ID                   BIGINT NOT NULL,
    NAME                 VARCHAR(100) NOT NULL,
    AGE                  BIGINT,
    STARS                INT,
    LOCATION             VARCHAR(200),
    NOTE                 TEXT
);
-- sequence
CREATE SEQUENCE PLANET_SYSTEM_SEQ START WITH 1001 INCREMENT BY 1;
-- index
ALTER TABLE PLANET_SYSTEM ADD CONSTRAINT PKPS_ID PRIMARY KEY (ID);
-- comment
COMMENT ON TABLE PLANET_SYSTEM IS 'Entity representing planet system.';
COMMENT ON COLUMN PLANET_SYSTEM.ID IS 'Planet system identifier. Primary Key.';
COMMENT ON COLUMN PLANET_SYSTEM.NAME IS 'Name of the planet system.';
COMMENT ON COLUMN PLANET_SYSTEM.AGE IS 'Age of the planet system.';
COMMENT ON COLUMN PLANET_SYSTEM.STARS IS 'Number of stars into the planet system.';
COMMENT ON COLUMN PLANET_SYSTEM.LOCATION IS 'Location of the planet system.';
COMMENT ON COLUMN PLANET_SYSTEM.NOTE IS 'Note of the planet system.';

-- table
CREATE TABLE PLANET (
    ID                   BIGINT NOT NULL,
    NAME                 VARCHAR(100) NOT NULL,
    SYSTEM_ID            BIGINT,
    TYPE                 PLANET_TYPE,
    SIGN                 CHAR(1),
    NOTE                 TEXT
);
-- sequence
CREATE SEQUENCE PLANET_SEQ START WITH 1001 INCREMENT BY 1;
-- index
ALTER TABLE PLANET ADD CONSTRAINT PKP_ID PRIMARY KEY (ID);
ALTER TABLE PLANET ADD CONSTRAINT FKP_SYSTEM_ID FOREIGN KEY (SYSTEM_ID) REFERENCES PLANET_SYSTEM(ID);
-- comment
COMMENT ON TABLE PLANET IS 'Entity representing planet.';
COMMENT ON COLUMN PLANET.ID IS 'Planet identifier. Primary Key.';
COMMENT ON COLUMN PLANET.NAME IS 'Name of the planet.';
COMMENT ON COLUMN PLANET.SYSTEM_ID IS 'ID of the planet system.';
COMMENT ON COLUMN PLANET.TYPE IS 'Type of the planet.';
COMMENT ON COLUMN PLANET.SIGN IS 'Sign of the planet.';
COMMENT ON COLUMN PLANET.NOTE IS 'Note of the planet.';

-- table
CREATE TABLE PLANET_ATTRIBUTE (
    ID                   BIGINT NOT NULL,
    PLANET_ID            BIGINT NOT NULL,
    DIAMETER             NUMERIC(10, 3),
    MASS                 NUMERIC(10, 2),
    AXIS                 NUMERIC(10, 2),
    PERIOD               NUMERIC(10, 2),
    INCLINATION          NUMERIC(5, 2),
    ECCENTRICITY         NUMERIC(5, 3),
    ROTATION             NUMERIC(10, 2),
    MOONS                INT,
    RINGS                BOOLEAN
);
-- sequence
CREATE SEQUENCE PLANET_ATTRIBUTE_SEQ START WITH 1001 INCREMENT BY 1;
-- index
ALTER TABLE PLANET_ATTRIBUTE ADD CONSTRAINT PKPA_ID PRIMARY KEY (ID);
ALTER TABLE PLANET_ATTRIBUTE ADD CONSTRAINT FKPA_PLANET_ID FOREIGN KEY (PLANET_ID) REFERENCES PLANET(ID);
-- comment
COMMENT ON TABLE PLANET_ATTRIBUTE IS 'Entity representing planet attribute.';
COMMENT ON COLUMN PLANET_ATTRIBUTE.ID IS 'Planet attribute identifier. Primary Key.';
COMMENT ON COLUMN PLANET_ATTRIBUTE.PLANET_ID IS 'Owning planet identifier. Foreign Key.';
COMMENT ON COLUMN PLANET_ATTRIBUTE.DIAMETER IS 'Diameter of the planet.';
COMMENT ON COLUMN PLANET_ATTRIBUTE.MASS IS 'Mass of the planet.';
COMMENT ON COLUMN PLANET_ATTRIBUTE.AXIS IS 'Axis of the planet.';
COMMENT ON COLUMN PLANET_ATTRIBUTE.PERIOD IS 'Period of the planet.';
COMMENT ON COLUMN PLANET_ATTRIBUTE.INCLINATION IS 'Inclination of the planet.';
COMMENT ON COLUMN PLANET_ATTRIBUTE.ECCENTRICITY IS 'Eccentricity of the planet.';
COMMENT ON COLUMN PLANET_ATTRIBUTE.ROTATION IS 'Rotation of the planet.';
COMMENT ON COLUMN PLANET_ATTRIBUTE.MOONS IS 'Number of moons of the planet.';
COMMENT ON COLUMN PLANET_ATTRIBUTE.RINGS IS 'Presence of rings of the planet.';

-- table
CREATE TABLE PLANET_MOON (
    ID                   BIGINT NOT NULL,
    PLANET_ID            BIGINT NOT NULL,
    NAME                 VARCHAR(100) NOT NULL,
    DISTANCE             NUMERIC(10, 2),
    RADIUS               NUMERIC(10, 3),
    NOTE                 TEXT
);
-- sequence
CREATE SEQUENCE PLANET_MOON_SEQ START WITH 1001 INCREMENT BY 1;
-- index
ALTER TABLE PLANET_MOON ADD CONSTRAINT PKPM_ID PRIMARY KEY (ID);
ALTER TABLE PLANET_MOON ADD CONSTRAINT FKPM_PLANET_ID FOREIGN KEY (PLANET_ID) REFERENCES PLANET(ID);
-- comment
COMMENT ON TABLE PLANET_MOON IS 'Entity representing planet moon.';
COMMENT ON COLUMN PLANET_MOON.ID IS 'Planet moon identifier. Primary Key.';
COMMENT ON COLUMN PLANET_MOON.PLANET_ID IS 'Owning planet identifier. Foreign Key.';
COMMENT ON COLUMN PLANET_MOON.NAME IS 'Name of the planet moon.';
COMMENT ON COLUMN PLANET_MOON.DISTANCE IS 'Distance of the planet moon.';
COMMENT ON COLUMN PLANET_MOON.RADIUS IS 'Radius of the planet moon.';
COMMENT ON COLUMN PLANET_MOON.NOTE IS 'Note of the planet moon.';

-- table
CREATE TABLE PLANET_ATMOSPHERE (
    ID                   BIGINT NOT NULL,
    NAME                 VARCHAR(100) NOT NULL,
    NOTE                 TEXT
);
-- sequence
CREATE SEQUENCE PLANET_ATMOSPHERE_SEQ START WITH 1001 INCREMENT BY 1;
-- index
ALTER TABLE PLANET_ATMOSPHERE ADD CONSTRAINT PKPT_ID PRIMARY KEY (ID);
-- comment
COMMENT ON TABLE PLANET_ATMOSPHERE IS 'Entity representing planet atmosphere.';
COMMENT ON COLUMN PLANET_ATMOSPHERE.ID IS 'Planet atmosphere identifier. Primary Key.';
COMMENT ON COLUMN PLANET_ATMOSPHERE.NAME IS 'Name of the planet atmosphere.';
COMMENT ON COLUMN PLANET_ATMOSPHERE.NOTE IS 'Note of the planet atmosphere.';

-- table
CREATE TABLE PLANET_ATMOSPHERE_MAP (
    PLANET_ID            BIGINT NOT NULL,
    ATMOSPHERE_ID        BIGINT NOT NULL
);
-- sequence
CREATE SEQUENCE PLANET_ATMOSPHERE_MAP_SEQ START WITH 1001 INCREMENT BY 1;
-- index
ALTER TABLE PLANET_ATMOSPHERE_MAP ADD CONSTRAINT PKPTM_ID PRIMARY KEY (PLANET_ID, ATMOSPHERE_ID);
ALTER TABLE PLANET_ATMOSPHERE_MAP ADD CONSTRAINT FKPTM_PLANET_ID FOREIGN KEY (PLANET_ID) REFERENCES PLANET(ID);
ALTER TABLE PLANET_ATMOSPHERE_MAP ADD CONSTRAINT FKPTM_ATMOSPHERE_ID FOREIGN KEY (ATMOSPHERE_ID) REFERENCES PLANET_ATMOSPHERE(ID);
-- comment
COMMENT ON TABLE PLANET_ATMOSPHERE_MAP IS 'Entity representing planet atmosphere mapping.';
COMMENT ON COLUMN PLANET_ATMOSPHERE_MAP.PLANET_ID IS 'Reference to the planet identifier.';
COMMENT ON COLUMN PLANET_ATMOSPHERE_MAP.ATMOSPHERE_ID IS 'Reference to the planet atmosphere identifier.';
