/*
 * This file is generated by jOOQ.
 */
package com.witalis.jkit.jooq.model.enums;


import com.witalis.jkit.jooq.model.Astronomy;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum PlanetType implements EnumType {

    GIANT("GIANT"),

    DWARF("DWARF"),

    TERRESTRIAL("TERRESTRIAL");

    private final String literal;

    private PlanetType(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Astronomy.ASTRONOMY;
    }

    @Override
    public String getName() {
        return "planet_type";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal
     */
    public static PlanetType lookupLiteral(String literal) {
        return EnumType.lookupLiteral(PlanetType.class, literal);
    }
}
