-- table
CREATE TABLE PLANET_ATTRIBUTE (
    ID                   BIGINT NOT NULL,
    PLANET_ID            BIGINT NOT NULL,
    DIAMETER             NUMERIC(10, 3),
    MASS                 NUMERIC(10, 2),
    AXIS                 NUMERIC(10, 2),
    PERIOD               NUMERIC(10, 2),
    INCLINATION          NUMERIC(5, 2),
    ECCENTRICITY         NUMERIC(5, 3),
    ROTATION             NUMERIC(10, 2),
    MOONS                INT,
    RINGS                BOOLEAN
);
-- sequence
CREATE SEQUENCE PLANET_ATTRIBUTE_SEQ START WITH 1001 INCREMENT BY 1;
-- index
ALTER TABLE PLANET_ATTRIBUTE ADD CONSTRAINT PKPA_ID PRIMARY KEY (ID);
ALTER TABLE PLANET_ATTRIBUTE ADD CONSTRAINT FKPA_PLANET_ID FOREIGN KEY (PLANET_ID) REFERENCES PLANET(ID);
-- comment
COMMENT ON TABLE PLANET_ATTRIBUTE IS 'Entity representing planet attribute.';
COMMENT ON COLUMN PLANET_ATTRIBUTE.ID IS 'Planet attribute identifier. Primary Key.';
COMMENT ON COLUMN PLANET_ATTRIBUTE.PLANET_ID IS 'Owning planet identifier. Foreign Key.';
COMMENT ON COLUMN PLANET_ATTRIBUTE.DIAMETER IS 'Diameter of the planet.';
COMMENT ON COLUMN PLANET_ATTRIBUTE.MASS IS 'Mass of the planet.';
COMMENT ON COLUMN PLANET_ATTRIBUTE.AXIS IS 'Axis of the planet.';
COMMENT ON COLUMN PLANET_ATTRIBUTE.PERIOD IS 'Period of the planet.';
COMMENT ON COLUMN PLANET_ATTRIBUTE.INCLINATION IS 'Inclination of the planet.';
COMMENT ON COLUMN PLANET_ATTRIBUTE.ECCENTRICITY IS 'Eccentricity of the planet.';
COMMENT ON COLUMN PLANET_ATTRIBUTE.ROTATION IS 'Rotation of the planet.';
COMMENT ON COLUMN PLANET_ATTRIBUTE.MOONS IS 'Number of moons of the planet.';
COMMENT ON COLUMN PLANET_ATTRIBUTE.RINGS IS 'Presence of rings of the planet.';
