-- table
CREATE TABLE PLANET_ATMOSPHERE_MAP (
    PLANET_ID            BIGINT NOT NULL,
    ATMOSPHERE_ID        BIGINT NOT NULL
);
-- sequence
CREATE SEQUENCE PLANET_ATMOSPHERE_MAP_SEQ START WITH 1001 INCREMENT BY 1;
-- index
ALTER TABLE PLANET_ATMOSPHERE_MAP ADD CONSTRAINT PKPTM_ID PRIMARY KEY (PLANET_ID, ATMOSPHERE_ID);
ALTER TABLE PLANET_ATMOSPHERE_MAP ADD CONSTRAINT FKPTM_PLANET_ID FOREIGN KEY (PLANET_ID) REFERENCES PLANET(ID);
ALTER TABLE PLANET_ATMOSPHERE_MAP ADD CONSTRAINT FKPTM_ATMOSPHERE_ID FOREIGN KEY (ATMOSPHERE_ID) REFERENCES PLANET_ATMOSPHERE(ID);
-- comment
COMMENT ON TABLE PLANET_ATMOSPHERE_MAP IS 'Entity representing planet atmosphere mapping.';
COMMENT ON COLUMN PLANET_ATMOSPHERE_MAP.PLANET_ID IS 'Reference to the planet identifier.';
COMMENT ON COLUMN PLANET_ATMOSPHERE_MAP.ATMOSPHERE_ID IS 'Reference to the planet atmosphere identifier.';
