/*
 * This file is generated by jOOQ.
 */
package com.witalis.jkit.jooq.model.tables.daos;


import com.witalis.jkit.jooq.model.tables.PlanetMoon;
import com.witalis.jkit.jooq.model.tables.records.PlanetMoonRecord;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * Entity representing planet moon.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlanetMoonDao extends DAOImpl<PlanetMoonRecord, com.witalis.jkit.jooq.model.tables.pojos.PlanetMoon, Long> {

    /**
     * Create a new PlanetMoonDao without any configuration
     */
    public PlanetMoonDao() {
        super(PlanetMoon.PLANET_MOON, com.witalis.jkit.jooq.model.tables.pojos.PlanetMoon.class);
    }

    /**
     * Create a new PlanetMoonDao with an attached configuration
     */
    public PlanetMoonDao(Configuration configuration) {
        super(PlanetMoon.PLANET_MOON, com.witalis.jkit.jooq.model.tables.pojos.PlanetMoon.class, configuration);
    }

    @Override
    public Long getId(com.witalis.jkit.jooq.model.tables.pojos.PlanetMoon object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.witalis.jkit.jooq.model.tables.pojos.PlanetMoon> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(PlanetMoon.PLANET_MOON.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.witalis.jkit.jooq.model.tables.pojos.PlanetMoon> fetchById(Long... values) {
        return fetch(PlanetMoon.PLANET_MOON.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.witalis.jkit.jooq.model.tables.pojos.PlanetMoon fetchOneById(Long value) {
        return fetchOne(PlanetMoon.PLANET_MOON.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.witalis.jkit.jooq.model.tables.pojos.PlanetMoon> fetchOptionalById(Long value) {
        return fetchOptional(PlanetMoon.PLANET_MOON.ID, value);
    }

    /**
     * Fetch records that have <code>planet_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.witalis.jkit.jooq.model.tables.pojos.PlanetMoon> fetchRangeOfPlanetId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(PlanetMoon.PLANET_MOON.PLANET_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>planet_id IN (values)</code>
     */
    public List<com.witalis.jkit.jooq.model.tables.pojos.PlanetMoon> fetchByPlanetId(Long... values) {
        return fetch(PlanetMoon.PLANET_MOON.PLANET_ID, values);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.witalis.jkit.jooq.model.tables.pojos.PlanetMoon> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(PlanetMoon.PLANET_MOON.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.witalis.jkit.jooq.model.tables.pojos.PlanetMoon> fetchByName(String... values) {
        return fetch(PlanetMoon.PLANET_MOON.NAME, values);
    }

    /**
     * Fetch records that have <code>distance BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.witalis.jkit.jooq.model.tables.pojos.PlanetMoon> fetchRangeOfDistance(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(PlanetMoon.PLANET_MOON.DISTANCE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>distance IN (values)</code>
     */
    public List<com.witalis.jkit.jooq.model.tables.pojos.PlanetMoon> fetchByDistance(BigDecimal... values) {
        return fetch(PlanetMoon.PLANET_MOON.DISTANCE, values);
    }

    /**
     * Fetch records that have <code>radius BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.witalis.jkit.jooq.model.tables.pojos.PlanetMoon> fetchRangeOfRadius(BigDecimal lowerInclusive, BigDecimal upperInclusive) {
        return fetchRange(PlanetMoon.PLANET_MOON.RADIUS, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>radius IN (values)</code>
     */
    public List<com.witalis.jkit.jooq.model.tables.pojos.PlanetMoon> fetchByRadius(BigDecimal... values) {
        return fetch(PlanetMoon.PLANET_MOON.RADIUS, values);
    }

    /**
     * Fetch records that have <code>note BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.witalis.jkit.jooq.model.tables.pojos.PlanetMoon> fetchRangeOfNote(String lowerInclusive, String upperInclusive) {
        return fetchRange(PlanetMoon.PLANET_MOON.NOTE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>note IN (values)</code>
     */
    public List<com.witalis.jkit.jooq.model.tables.pojos.PlanetMoon> fetchByNote(String... values) {
        return fetch(PlanetMoon.PLANET_MOON.NOTE, values);
    }
}
