/*
 * This file is generated by jOOQ.
 */
package com.witalis.jkit.jooq.model.tables.daos;


import com.witalis.jkit.jooq.model.tables.PlanetAtmosphereMap;
import com.witalis.jkit.jooq.model.tables.records.PlanetAtmosphereMapRecord;

import java.util.List;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * Entity representing planet atmosphere mapping.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlanetAtmosphereMapDao extends DAOImpl<PlanetAtmosphereMapRecord, com.witalis.jkit.jooq.model.tables.pojos.PlanetAtmosphereMap, Record2<Long, Long>> {

    /**
     * Create a new PlanetAtmosphereMapDao without any configuration
     */
    public PlanetAtmosphereMapDao() {
        super(PlanetAtmosphereMap.PLANET_ATMOSPHERE_MAP, com.witalis.jkit.jooq.model.tables.pojos.PlanetAtmosphereMap.class);
    }

    /**
     * Create a new PlanetAtmosphereMapDao with an attached configuration
     */
    public PlanetAtmosphereMapDao(Configuration configuration) {
        super(PlanetAtmosphereMap.PLANET_ATMOSPHERE_MAP, com.witalis.jkit.jooq.model.tables.pojos.PlanetAtmosphereMap.class, configuration);
    }

    @Override
    public Record2<Long, Long> getId(com.witalis.jkit.jooq.model.tables.pojos.PlanetAtmosphereMap object) {
        return compositeKeyRecord(object.getPlanetId(), object.getAtmosphereId());
    }

    /**
     * Fetch records that have <code>planet_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.witalis.jkit.jooq.model.tables.pojos.PlanetAtmosphereMap> fetchRangeOfPlanetId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(PlanetAtmosphereMap.PLANET_ATMOSPHERE_MAP.PLANET_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>planet_id IN (values)</code>
     */
    public List<com.witalis.jkit.jooq.model.tables.pojos.PlanetAtmosphereMap> fetchByPlanetId(Long... values) {
        return fetch(PlanetAtmosphereMap.PLANET_ATMOSPHERE_MAP.PLANET_ID, values);
    }

    /**
     * Fetch records that have <code>atmosphere_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.witalis.jkit.jooq.model.tables.pojos.PlanetAtmosphereMap> fetchRangeOfAtmosphereId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(PlanetAtmosphereMap.PLANET_ATMOSPHERE_MAP.ATMOSPHERE_ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>atmosphere_id IN (values)</code>
     */
    public List<com.witalis.jkit.jooq.model.tables.pojos.PlanetAtmosphereMap> fetchByAtmosphereId(Long... values) {
        return fetch(PlanetAtmosphereMap.PLANET_ATMOSPHERE_MAP.ATMOSPHERE_ID, values);
    }
}
