/*
 * This file is generated by jOOQ.
 */
package com.witalis.jkit.jooq.model.tables.daos;


import com.witalis.jkit.jooq.model.tables.PlanetAtmosphere;
import com.witalis.jkit.jooq.model.tables.records.PlanetAtmosphereRecord;

import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * Entity representing planet atmosphere.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlanetAtmosphereDao extends DAOImpl<PlanetAtmosphereRecord, com.witalis.jkit.jooq.model.tables.pojos.PlanetAtmosphere, Long> {

    /**
     * Create a new PlanetAtmosphereDao without any configuration
     */
    public PlanetAtmosphereDao() {
        super(PlanetAtmosphere.PLANET_ATMOSPHERE, com.witalis.jkit.jooq.model.tables.pojos.PlanetAtmosphere.class);
    }

    /**
     * Create a new PlanetAtmosphereDao with an attached configuration
     */
    public PlanetAtmosphereDao(Configuration configuration) {
        super(PlanetAtmosphere.PLANET_ATMOSPHERE, com.witalis.jkit.jooq.model.tables.pojos.PlanetAtmosphere.class, configuration);
    }

    @Override
    public Long getId(com.witalis.jkit.jooq.model.tables.pojos.PlanetAtmosphere object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.witalis.jkit.jooq.model.tables.pojos.PlanetAtmosphere> fetchRangeOfId(Long lowerInclusive, Long upperInclusive) {
        return fetchRange(PlanetAtmosphere.PLANET_ATMOSPHERE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.witalis.jkit.jooq.model.tables.pojos.PlanetAtmosphere> fetchById(Long... values) {
        return fetch(PlanetAtmosphere.PLANET_ATMOSPHERE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.witalis.jkit.jooq.model.tables.pojos.PlanetAtmosphere fetchOneById(Long value) {
        return fetchOne(PlanetAtmosphere.PLANET_ATMOSPHERE.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.witalis.jkit.jooq.model.tables.pojos.PlanetAtmosphere> fetchOptionalById(Long value) {
        return fetchOptional(PlanetAtmosphere.PLANET_ATMOSPHERE.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.witalis.jkit.jooq.model.tables.pojos.PlanetAtmosphere> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(PlanetAtmosphere.PLANET_ATMOSPHERE.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.witalis.jkit.jooq.model.tables.pojos.PlanetAtmosphere> fetchByName(String... values) {
        return fetch(PlanetAtmosphere.PLANET_ATMOSPHERE.NAME, values);
    }

    /**
     * Fetch records that have <code>note BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.witalis.jkit.jooq.model.tables.pojos.PlanetAtmosphere> fetchRangeOfNote(String lowerInclusive, String upperInclusive) {
        return fetchRange(PlanetAtmosphere.PLANET_ATMOSPHERE.NOTE, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>note IN (values)</code>
     */
    public List<com.witalis.jkit.jooq.model.tables.pojos.PlanetAtmosphere> fetchByNote(String... values) {
        return fetch(PlanetAtmosphere.PLANET_ATMOSPHERE.NOTE, values);
    }
}
